### ISSUE TITLE
Error when trying to parse quotes in JSX

### ISSUE THREAD

**Issue by sergi** [vvakame/typescript-formatter#46]
Typescript formatter would exit with an error when parsing the following line:

`const title = <span>A call in the room <span className="room-name">"{ result.room }"</span></span>;`

Changing it into the following line solved the error:

`const title = <span>A call in the room <span className="room-name">&ldquo;{ result.room }&rdquo; </span></span>;`

The solution was particularly hard to find out because the error was completely non-descriptive:

```
> tsfmt -r

Error: Debug Failure. False expression:
    at Object.assert (web/node_modules/typescript/lib/typescript.js:1721:23)
    at processChildNode (web/node_modules/typescript/lib/typescript.js:46156:34)
    at web/node_modules/typescript/lib/typescript.js:46107:21
    at visitNode (web/node_modules/typescript/lib/typescript.js:7243:20)
    at Object.forEachChild (web/node_modules/typescript/lib/typescript.js:7359:24)
    at processNode (web/node_modules/typescript/lib/typescript.js:46106:20)
    at processChildNode (web/node_modules/typescript/lib/typescript.js:46162:21)
```

Using typescript-formatter 2.2.0 with Typescript 1.8.10. Using the following `tslint.json`:

``` json
{
    "rules": {
        "class-name": true,
        "comment-format": [
            true,
            "check-space"
        ],
        "indent": [
            true,
            "spaces"
        ],
        "curly": true,
        "no-eval": true,
        "no-internal-module": true,
        "no-inferrable-types": [true, "ignore-params"],
        "no-trailing-whitespace": true,
        "trailing-comma": [true, {"multiline": "always", "singleline": "never"}],
        "no-var-keyword": true,
        "no-var-requires": true,
        "no-require-imports": true,
        "no-angle-bracket-type-assertion": true,
        "no-consecutive-blank-lines": true,
        "one-variable-per-declaration": [true, "ignore-for-loop"],
        "one-line": [
            true,
            "check-open-brace",
            "check-whitespace"
        ],
        "quotemark": [
            false,
            "single"
        ],
        "semicolon": [
            true,
            "always"
        ],
        "triple-equals": [
            true,
            "allow-null-check"
        ],
        "typedef-whitespace": [
            true,
            {
                "call-signature": "nospace",
                "index-signature": "nospace",
                "parameter": "nospace",
                "property-declaration": "nospace",
                "variable-declaration": "nospace"
            }
        ],
        "variable-name": [
            true,
            "ban-keywords"
        ],
        "no-invalid-this": true,
        "no-unused-variable": [true, "react"],
        "no-string-literal": true,
        "use-isnan": true,
        "whitespace": [
            true,
            "check-branch",
            "check-decl",
            "check-operator",
            "check-separator",
            "check-type"
        ]
    }
}
```

**Comment by vvakame** [comment]
https://github.com/Microsoft/TypeScript/issues/9122
is this same issue?

**Comment by simon-rocketmaker** [comment]
Can confirm same issue.
Broke Format Code: <label>Employer's National Insurance (%)</label>
Didn't break Format Code: <label>{`Employer's National Insurance (%)`}</label>
